In [26]:
#quiz
def tambah (a,b):
    print(a+b) 

def kurang(a,b):
    print(a-b)

def kali (a,b):
    print(a*b)

def bagi (a,b):
    print(a//b)

def pangkat (a,b):
    print(a**b)
    
try:
    a = int(input(" Masukan Angka 1 = "))
    c = input("Masukan Operator angkanya ")
    b = int(input("Masukan  Angka 2 = "))

    if c == "+":
        print(tambah(a,b))
    elif c =="-":
        kurang(a,b)
        print(kurang(a,b))
    elif c =="x":
        print(kali(a,b))
    elif c ==":":
        print(bagi(a,b))
    else:
        print("Operator tidak ditemukan")

except ValueError:
    print("Tipe data salah")

 Masukan Angka 1 = 21
Masukan Operator angkanya :
Masukan  Angka 2 = 1
21
None


# Array

In [24]:
import numpy as np

In [37]:
# one dimensional array
c = np.array([1,2,3]) 
d = np.array([1,2,3,4,5,6,7,8])
print(d[2:9])
print(c)

[3 4 5 6 7 8]
[1 2 3]


## Indexing dan slicing pada Array 

In [38]:
c[0]

1

In [39]:
c[1]

2

In [40]:
c[2]

3

In [41]:
array_1 = [1,2,3,4,5,6,7,8]
print(array_1[2:9])

[3, 4, 5, 6, 7, 8]


In [45]:
list_of_list = ([1,2,3],[4,5,6],[7,8,9])

array2=np.array(list_of_list)
print(array2) # array 2d axis = 0 row, axis 1 = colom
print(array2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [47]:
list_of_list2 = ([1,2],[4,5],[7,8])
array3 = np.array(list_of_list2)
print(array3)
print(array3.shape)

[[1 2]
 [4 5]
 [7 8]]
(3, 2)


## Creating Array

In [52]:
#zeros, mengisi array  dengan nilai 0

print(np.zeros(8)) #1d
print(np.zeros([3,2])) # 3 baris, 2 kolom, 2D

[0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [54]:
#np ones
print(np.ones(4))
print(np.ones((4,2))) # 4 baris, 2 kolom

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [55]:
#np empty

np.empty(5)
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [59]:
#np arange seperti range pada python
print(np.arange(10))
print(np.arange(0,10,2)) #strat, stop, step

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [61]:
print(np.arange(30))
print(" ")
print(np.arange(0,30,4)) #strat, stop, step

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
 
[ 0  4  8 12 16 20 24 28]


In [62]:
c = np.array([1,2,3,4,5,6,7,8,9])

#append
np.append(c,[10,11])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
#delet
c = np.array([1,2,3,4,5,6,7,8,9])
np.delete(c,2)

array([1, 2, 4, 5, 6, 7, 8, 9])

In [67]:
#sort
np.sort(c)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
print(c.ndim)

1


In [70]:
d = np.zeros((2,2))
print(d.ndim) #2dimensi

2


In [71]:
#size; melihat izi dari datanya
print(c.size)
print(d.size)

9
4


In [74]:
# reshape : harus bisa dibagi datanya, kalau tidak bisa akan eror
print(c.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [79]:
array3 = np.array([[1,2,3,4]]) # kalau sudah ada [[ sudah jadi 2d array
array3.shape

(1, 4)

In [84]:
#np.axis
array4 = np.array([4,5,6])
array4

print(array4[np.newaxis,:])
print(array4[:,np.newaxis])

[[4 5 6]]
[[4]
 [5]
 [6]]


In [88]:
#np.expand_dims
array7 = np.array([3,4,5,6,7,8,9])
array8 = np.expand_dims(array7,axis=1) #membuat 1d jadi 2d dengan menambahkan baris
print(array8)
print(array8.shape)
print(" ")
array8 = np.expand_dims(array7,axis=0) #membuat 1d jadi 2d dengan menambahkan kolom
print(array8)
print(array8.shape)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(7, 1)
 
[[3 4 5 6 7 8 9]]
(1, 7)


In [89]:
#operasi matematika array broadcasting
array7+2

array([ 5,  6,  7,  8,  9, 10, 11])

In [90]:
array7*2

array([ 6,  8, 10, 12, 14, 16, 18])

In [91]:
array_10 = np.array([[1,2,3,4],[5,6,7,8]])

array_10+4

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [95]:
#filteringarray lebih baik untuk 1d
array_l1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_l1[array_l1>4])

[5 6 7 8 9]


In [94]:

array7[array7>5]
array7[array7==8]

array([8])

## Quiz 2

In [132]:
def bintang(baris):
    kolom = baris *2 -1
    spasi = 0
    hasil = ""
    for i in range(baris):
        for j in range(spasi):
            hasil += " "
        for j in range(kolom):
            if i == 0:
                simbol = "*"
            elif i == baris -1:
                simbol =  "*"
            elif j == 0 or j == kolom -1 :
                simbol = "*"
            else :
                simbol = "*"
            hasil += simbol
        kolom -= 2
        spasi += 1
        if baris ==1 :
            hasil += ""
        else:
            hasil += "\n"
    baris = baris -1
    kolom = 3
    spasi = baris -1
    for i in range(baris):
        for j in range(spasi):
            hasil += " "
        for j in range(kolom):
            if j == 0 or j == kolom -1:
                simbol = "*"
            elif i == baris -1:
                simbol = "*"
            else :
                simbol = "*"
            hasil += simbol
        kolom += 2
        spasi -= 1
        if i != baris -1:
            hasil += "\n"
        else :
            hasil+=""
    return hasil
ok = int(input())
print (bintang(ok))

10
*******************
 *****************
  ***************
   *************
    ***********
     *********
      *******
       *****
        ***
         *
        ***
       *****
      *******
     *********
    ***********
   *************
  ***************
 *****************
*******************


In [117]:
def bintang(baris):
    kolom = baris *2 -1
    spasi = 0
    hasil = ""
    for i in range(baris):
        for j in range(spasi):
            hasil += " "
        for j in range(kolom):
            if i == 0:
                simbol = "*"
            elif i == baris -1:
                simbol =  "."
            elif j == 0 or j == kolom -1 :
                simbol = "*"
            else :
                simbol = "."
            hasil += simbol
        kolom -= 2
        spasi += 1
        if baris ==1 :
            hasil += ""
        else:
            hasil += "\n"

ok = int(input())
print (bintang(ok))

10
None


In [134]:
tinggi = int(input('Input: '))
print()

for i in range(tinggi):
  for j in range(i+1):
    print(' ',end='')
     
  for k in range(tinggi-i):
    print('* ',end='')
  print()
for i in range(tinggi):
  print(' ' * (tinggi-i),end='')
  print('* ' * (i+1))

Input: 5

 * * * * * 
  * * * * 
   * * * 
    * * 
     * 
     * 
    * * 
   * * * 
  * * * * 
 * * * * * 


## Hstack dan Vstack, hsplit, vsplit 

In [137]:
array_14  = np.array([3,4,5,6,7])
array_15 = np.array([7,8,9,10,11])
print(np.vstack([array_14,array_15])) #vertical
print(np.hstack([array_14,array_15])) #horizontal

[[ 3  4  5  6  7]
 [ 7  8  9 10 11]]
[ 3  4  5  6  7  7  8  9 10 11]


In [138]:
array_14  = np.array([3,4,5,6,7,8])
array_split=np.hsplit(array_14,2)
print(array_split)

[array([3, 4, 5]), array([6, 7, 8])]


In [142]:
array_19=np.array([[1,2,3,4],[4,5,6,7]])
print(array_19)
print("Horizontal split")
print(np.hsplit(array_19,2))
print("Vertical split")
print(np.vsplit(array_19,2))

[[1 2 3 4]
 [4 5 6 7]]
Horizontal split
[array([[1, 2],
       [4, 5]]), array([[3, 4],
       [6, 7]])]
Vertical split
[array([[1, 2, 3, 4]]), array([[4, 5, 6, 7]])]


In [144]:
array_a =np.array([1,2,3])
array_b =np.array([3,4,5])
print(array_a+array_b)

[4 6 8]


In [145]:
array_c =np.array([[1,2,3],[4,5,6]])
array_d =np.array([[7,8,9],[10,11,12]])

print(array_c-array_d)

[[-6 -6 -6]
 [-6 -6 -6]]


In [153]:
array_a =np.array([1,2,3])
array_b =np.array([3,4,5])
array_c =np.array([[1,2,3],
                   [4,5,6]])
array_d =np.array([[7,8,9],
                   [10,11,12]])

print(array_a.sum())
print(array_b.sum())
print(array_c.sum(axis=0)) #penjumalah kebawah
print(array_c.sum(axis=1)) #penjumalah kesamping
print(array_a.max())
print(array_c.max())
print(array_c.max(axis=1))
print(array_a.min())
print(array_c.min())
print(array_c.min(axis=1))

6
12
[5 7 9]
[ 6 15]
3
6
[3 6]
1
1
[1 4]


##Transposing 

In [154]:
array_a =np.array([1,2,3])
array_b =np.array([3,4,5])
array_c =np.array([[1,2,3],
                   [4,5,6]])
array_d =np.array([[7,8,9],
                   [10,11,12]])

print(array_c)
print(array_c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [156]:
print(array_c.T)
print(array_c.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [158]:
arrayd  =np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arrayd)
print(arrayd.T)
print(arrayd.T.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
(5, 3)


In [165]:
array_random = np.random.random([3,2])
print(array_random)
print(array_random.flatten())

[[0.71908766 0.806905  ]
 [0.60803817 0.83460347]
 [0.70637376 0.99671904]]
[0.71908766 0.806905   0.60803817 0.83460347 0.70637376 0.99671904]


## math Formulas Numpy 

In [167]:
array_random = np.random.random([3,2])*100
print(array_random)
np.sum(array_random)

[[53.68388976 89.06915164]
 [ 6.56199431 31.15285653]
 [74.36101289 80.64067993]]


335.46958506549794

In [168]:
np.square(9)

81

In [169]:
np.sqrt(9)

3.0

In [170]:
a = np.log(1000000)

13.815510557964274

In [172]:
np.exp(a)

1318815734.4832146

In [190]:
#Prime number generator base interval
#bilangan prima bilangan habis dibagi 1 dan  bilangan itu tsb
lower = int(input("Please, Enter the lowest Range Value :"))
upper = int(input("Please, Enter the Upper Range Value :"))
print("The prime Numbers in the range are ",lower,"hingga",upper,":")
for num in range(lower,upper + 1):

    if num > 1:
        for i in range(2, num):
            if (num % i) == 0:
                break
        else:
            print(num)

Please, Enter the lowest Range Value :10
Please, Enter the Upper Range Value :20
The prime Numbers in the range are  10 hingga 20 :
11
13
17
19


In [181]:
5 % 2

1

In [188]:
for i in range(3,6+1):
    print(i)

3
4
5
6


In [183]:
print(range)

<class 'range'>
